<a href="https://colab.research.google.com/github/anas1IA/TP_DEEP_Learning/blob/main/last_one_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder


In [18]:
data = "winequality-red.csv"

In [19]:
df  = pd.read_csv(data)

In [20]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [32]:
df["quality"].unique()

array([5, 6, 7, 4, 8, 3])

In [21]:
# Separate features and target
X = df.iloc[:, :-1].values  # Features
y = df.iloc[:, -1].values   # Target

In [22]:
y = LabelEncoder().fit_transform(y)

In [23]:
y

array([2, 2, 2, ..., 3, 2, 3])

In [24]:


# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)




In [25]:
y_train

array([3, 3, 3, ..., 2, 4, 3])

In [26]:
# # Convert data to PyTorch tensors with the correct data type
# X_train, X_test = torch.tensor(X_train, dtype=torch.float32), torch.tensor(X_test, dtype=torch.float32)
# y_train, y_test = torch.tensor(y_train, dtype=torch.float32), torch.tensor(y_test, dtype=torch.float32)

In [27]:
# X_test = X_test.long()
# y_test = y_test.float()

In [28]:
# class NeuralNet(nn.Module):
#     def __init__(self, input_size, hidden_size, num_classes):
#         super(NeuralNet, self).__init__()
#         self.fc1 = nn.Linear(input_size, hidden_size)
#         self.relu = nn.ReLU()
#         self.fc2 = nn.Linear(hidden_size, num_classes)

#     def forward(self, x):
#         out = self.fc1(x)
#         out = self.relu(out)
#         out = self.fc2(out)
#         return out


In [29]:
# input_size = 11
# hidden_size = 64
# num_classes = 1
# learning_rate = 0.01

# model = NeuralNet(input_size, hidden_size, num_classes)
# criterion = nn.MSELoss()
# optimizer = optim.SGD(model.parameters(), lr=learning_rate)


In [30]:
# num_epochs = 100
# batch_size = 64

# for epoch in range(num_epochs):
#     for i in range(0, len(X_train), batch_size):
#         inputs = X_train[i:i+batch_size]
#         labels = y_train[i:i+batch_size]

#         # Forward pass
#         outputs = model(inputs)
#         loss = criterion(outputs, labels)

#         # Backward and optimize
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()

#     # Print progress
#     if (epoch+1) % 10 == 0:
#         print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')


In [38]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Assuming you have X_train, X_test, y_train, y_test loaded

# Convert data to PyTorch tensors
X_train, X_test = torch.tensor(X_train, dtype=torch.float32), torch.tensor(X_test, dtype=torch.float32,requires_grad=True)
y_train, y_test = torch.tensor(y_train, dtype=torch.long), torch.tensor(y_test, dtype=torch.long)  # Use torch.long for class labels

print(y_train)

# Create DataLoader
train_data = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_data, batch_size=100, shuffle=True)

# Define your neural network model
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc1 = nn.Linear(11, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 6)  # 5 output classes

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Initialize model, loss, and optimizer
model = MyModel()
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

# Training loop
num_epochs = 500
for epoch in range(num_epochs):
    model.train()
    for inputs, targets in train_loader:
        #print(targets)
        optimizer.zero_grad()
        outputs = model(inputs)
        # y_pred_probs = torch.softmax(outputs, dim=1).argmax(dim=1)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

    if epoch%50==0:
      print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}')

# Evaluation
model.eval()
with torch.no_grad():
    outputs = model(X_test)
    _, predicted = torch.max(outputs, 1)
    accuracy = (predicted == y_test).sum().item() / len(y_test)
    print(f'Accuracy: {accuracy}')


<ipython-input-38-0475613c4bcc>:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train, X_test = torch.tensor(X_train, dtype=torch.float32), torch.tensor(X_test, dtype=torch.float32,requires_grad=True)
<ipython-input-38-0475613c4bcc>:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train, y_test = torch.tensor(y_train, dtype=torch.long), torch.tensor(y_test, dtype=torch.long)  # Use torch.long for class labels


tensor([3, 3, 3,  ..., 2, 4, 3])
Epoch [1/500], Loss: 1.777799367904663
Epoch [51/500], Loss: 1.4940292835235596
Epoch [101/500], Loss: 1.3410155773162842
Epoch [151/500], Loss: 1.2691259384155273
Epoch [201/500], Loss: 1.1242549419403076
Epoch [251/500], Loss: 1.0502610206604004
Epoch [301/500], Loss: 1.0782357454299927
Epoch [351/500], Loss: 1.1008415222167969
Epoch [401/500], Loss: 1.0664238929748535
Epoch [451/500], Loss: 0.8735988736152649
Accuracy: 0.546875
